# Generated by Django 5.1.6 on 2025-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_items_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="media/%Y%m%d")),
            ],
        ),
    ]
